import React, { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    browse: 'Browse',
    organizers: 'Organizers',
    myTickets: 'My Tickets',
    signOut: 'Sign Out',
    logIn: 'Log In',
    signUp: 'Sign Up',
    theme: 'Theme',
    badge: 'New: Organizer Dashboard v2.0',
    heroTitle1: 'Events managed',
    heroTitle2: 'the smart way.',
    heroDesc: 'Create, manage and sell your tickets in just a few clicks. Whether in-person, virtual or hybrid, SmartEvent handles it all.',
    launchEvent: 'Launch an Event',
    exploreFeatures: 'Explore Features',
    searchEvent: 'Event',
    searchEventPlaceholder: 'Concert, Training, Tech...',
    searchWhere: 'Where?',
    searchWherePlaceholder: 'Paris, Lyon or Virtual',
    searchWhen: 'When?',
    searchBtn: 'Search',
    solutionTitle: 'A complete solution',
    solutionDesc: 'Everything you need to make your event a success.',
    organizersTitle: 'For Organizers',
    organizersFeatures: [
      'Multi-ticket event creation',
      'Real-time analytics dashboard',
      'Smart capacity management',
      'Direct messaging with attendees',
    ],
    participantsTitle: 'For Attendees',
    participantsFeatures: [
      'Secure booking and payment',
      'Google Calendar & Outlook sync',
      'Automatic notifications and reminders',
      'Feedback and rating system',
    ],
    register: {
      title: 'Create an account',
      subtitle: 'Join the SmartEvent community',
      fullName: 'Full name',
      fullNamePlaceholder: 'Ex: John Doe',
      email: 'Email address',
      emailPlaceholder: 'john.doe@example.com',
      password: 'Password',
      passwordPlaceholder: '•••••••• (8 chars min.)',
      role: 'You are?',
      roleAttendee: '🎟️ I am an Attendee',
      roleOrganizer: '🏢 I am an Organizer',
      submit: 'Create my account',
      alreadyRegistered: 'Already registered?',
      logIn: 'Log in',
      backHome: '← Back to home',
    },
    login: {
  title: 'Log In',
  subtitle: 'Welcome back!',
  email: 'Email address',
  emailPlaceholder: 'example@email.com',
  password: 'Password',
  passwordPlaceholder: '••••••••',
  submit: 'Log in',
  submitting: 'Logging in...',
  noAccount: 'No account yet?',
  signUp: 'Sign up',
  backHome: '← Back to home',
  defaultError: 'Invalid credentials or account not found',
  networkError: 'An error occurred while logging in.',
},
explore: {
  pageTitle: 'Explore Events | SmartEvent',
  title: 'Explore',
  titleHighlight: 'Experiences',
  subtitle: 'Discover unique events tailored to your interests.',
  searchPlaceholder: 'Search for an event...',
  virtual: 'Virtual',
  inPerson: 'In-person',
  price: 'Price',
  free: 'Free',
  viewDetails: 'View details',
  noResults: 'No events found',
  noResultsDesc: 'Try a different search or category.',
},

eventDetails: {
  loading: 'Loading...',
  notFound: 'Event not found',
  organizedBy: 'Organized by',
  about: 'About this event',
  location: '📍 Location',
  dateTime: 'Date & Time:',
  entryFee: 'Entry fee',
  free: 'Free',
  reserve: 'Book my ticket',
  processing: 'Processing...',
  soldOut: 'Sold Out',
  loginRequired: 'You must be logged in to book.',
  loginBtn: 'Log in',
  spotsLeft: 'Spots remaining:',
  loginRedirectMsg: 'Please log in to make a booking.',
  successMsg: "Your ticket is booked. Redirecting to 'My Tickets'...",
  bookingError: 'Error during booking.',
  networkError: 'Network error during booking attempt.',
  loadError: 'Loading error: Event not found.',
},
ticketsPage: {
  pageTitle: 'My Tickets 🎟️',
  loading: 'Loading...',
  loginRequired: 'Please log in.',
  noBookings: 'You have no bookings yet.',
  location: 'Location',
},
footer: {
  tagline: '"Making every event memorable through simplified and intelligent management."',
  platformTitle: 'Platform',
  browseEvents: 'Browse Events',
  ticketing: 'Ticketing',
  virtualEvents: 'Virtual Events',
  companyTitle: 'Company',
  about: 'About us',
  contact: 'Contact us',
  blog: 'Blog & News',
  legalTitle: 'Legal',
  privacy: 'Privacy Policy',
  terms: 'Terms of Service',
  cookies: 'Cookie Settings',
  copyright: 'Smart Event Management Web Application. Built for excellence.',
},
  },
  fr: {
    browse: 'Parcourir',
    organizers: 'Organisateurs',
    myTickets: 'Mes billets',
    signOut: 'Déconnexion',
    logIn: 'Connexion',
    signUp: "S'inscrire",
    theme: 'Thème',
    badge: 'Nouveau : Dashboard Organisateur v2.0',
    heroTitle1: "L'événementiel",
    heroTitle2: 'en mode intelligent.',
    heroDesc: "Créez, gérez et vendez vos tickets en quelques clics. Que ce soit en présentiel, en virtuel ou en hybride, SmartEvent s'occupe de tout.",
    launchEvent: 'Lancer un événement',
    exploreFeatures: 'Explorer les fonctions',
    searchEvent: 'Événement',
    searchEventPlaceholder: 'Concert, Formation, Tech...',
    searchWhere: 'Où ça ?',
    searchWherePlaceholder: 'Paris, Lyon ou Virtuel',
    searchWhen: 'Quand ?',
    searchBtn: 'Rechercher',
    solutionTitle: 'Une solution complète',
    solutionDesc: 'Tout ce dont vous avez besoin pour réussir votre projet événementiel.',
    organizersTitle: 'Pour les Organisateurs',
    organizersFeatures: [
      "Création d'événements multi-tickets",
      'Dashboard analytique en temps réel',
      'Gestion intelligente des capacités',
      'Messagerie directe avec les inscrits',
    ],
    participantsTitle: 'Pour les Participants',
    participantsFeatures: [
      'Réservation et paiement sécurisé',
      'Synchronisation Google Calendar & Outlook',
      'Notifications et rappels automatiques',
      'Système de feedback et notations',
    ],
    register: {
      title: 'Créer un compte',
      subtitle: 'Rejoignez la communauté SmartEvent',
      fullName: 'Nom complet',
      fullNamePlaceholder: 'Ex: Jean Dupont',
      email: 'Adresse Email',
      emailPlaceholder: 'jean.dupont@exemple.com',
      password: 'Mot de passe',
      passwordPlaceholder: '•••••••• (8 caract. min.)',
      role: 'Vous êtes ?',
      roleAttendee: '🎟️ Je suis un Participant',
      roleOrganizer: '🏢 Je suis un Organisateur',
      submit: 'Créer mon compte',
      alreadyRegistered: 'Déjà inscrit ?',
      logIn: 'Se connecter',
      backHome: "← Retour à l'accueil",
    },
    login: {
  title: 'Log In',
  subtitle: 'Welcome back!',
  email: 'Email address',
  emailPlaceholder: 'example@email.com',
  password: 'Password',
  passwordPlaceholder: '••••••••',
  submit: 'Log in',
  submitting: 'Logging in...',
  noAccount: 'No account yet?',
  signUp: 'Sign up',
  backHome: '← Back to home',
  defaultError: 'Invalid credentials or account not found',
  networkError: 'An error occurred while logging in.',
},
explore: {
  pageTitle: 'Explorer les événements | SmartEvent',
  title: 'Explorez les',
  titleHighlight: 'Expériences',
  subtitle: "Découvrez des événements uniques adaptés à vos centres d'intérêt.",
  searchPlaceholder: 'Rechercher un événement...',
  virtual: 'Virtuel',
  inPerson: 'Présentiel',
  price: 'Prix',
  free: 'Gratuit',
  viewDetails: 'Voir détails',
  noResults: 'Aucun événement trouvé',
  noResultsDesc: 'Essayez une autre recherche ou une autre catégorie.',
},
eventDetails: {
  loading: 'Chargement...',
  notFound: 'Événement introuvable',
  organizedBy: 'Organisé par',
  about: 'À propos de cet événement',
  location: '📍 Lieu',
  dateTime: 'Date et Heure :',
  entryFee: "Tarif d'entrée",
  free: 'Gratuit',
  reserve: 'Réserver mon ticket',
  processing: 'Traitement...',
  soldOut: 'Complet',
  loginRequired: 'Vous devez être connecté pour réserver.',
  loginBtn: 'Se connecter',
  spotsLeft: 'Places restantes :',
  loginRedirectMsg: 'Veuillez vous connecter pour réserver.',
  successMsg: "Votre ticket est réservé. Redirection vers 'Mes Billets'...",
  bookingError: 'Erreur lors de la réservation.',
  networkError: 'Erreur réseau lors de la tentative de réservation.',
  loadError: 'Erreur de chargement : Événement introuvable.',
},
ticketsPage: {
  pageTitle: 'Mes Billets 🎟️',
  loading: 'Chargement...',
  loginRequired: 'Veuillez vous connecter.',
  noBookings: "Vous n'avez pas encore de réservations.",
  location: 'Lieu',
},
footer: {
  tagline: '"Rendre chaque événement mémorable grâce à une gestion simplifiée et intelligente."',
  platformTitle: 'Plateforme',
  browseEvents: 'Parcourir les événements',
  ticketing: 'Billetterie',
  virtualEvents: 'Événements Virtuels',
  companyTitle: 'Société',
  about: 'À propos',
  contact: 'Contactez-nous',
  blog: 'Blog & Actualités',
  legalTitle: 'Légal',
  privacy: 'Confidentialité',
  terms: 'CGU / CGV',
  cookies: 'Gestion des cookies',
  copyright: "Smart Event Management Web Application. Développé pour l'excellence.",
},
  },
};

type Lang = 'en' | 'fr';
type Translations = typeof translations.en;

interface LangContextType {
  lang: Lang;
  toggleLang: () => void;
  t: Translations;
}

const LangContext = createContext<LangContextType | undefined>(undefined);

export const LangProvider = ({ children }: { children: React.ReactNode }) => {
  const [lang, setLang] = useState<Lang>('fr');
  const toggleLang = () => setLang((prev) => (prev === 'fr' ? 'en' : 'fr'));
  const t = translations[lang];

  return (
    <LangContext.Provider value={{ lang, toggleLang, t }}>
      {children}
    </LangContext.Provider>
  );
};

export const useLang = () => {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error('useLang must be used within a LangProvider');
  return ctx;
};